// <auto-generated />
namespace Inview.Epi.EpiFund.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ChangingHowDetailsStored : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangingHowDetailsStored));
        
        string IMigrationMetadata.Id
        {
            get { return "201406052240000_ChangingHowDetailsStored"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
