// <auto-generated />
namespace Inview.Epi.EpiFund.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeAssetListingAgents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeAssetListingAgents));
        
        string IMigrationMetadata.Id
        {
            get { return "201505271618425_removeAssetListingAgents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
