// <auto-generated />
namespace Inview.Epi.EpiFund.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEscrowFieldsToAsset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEscrowFieldsToAsset));
        
        string IMigrationMetadata.Id
        {
            get { return "201506011640386_addEscrowFieldsToAsset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
